module.exports = {
  admin:{
    files:[
      {
        src:[
          'app/public/admin/js/app.src.js'
        ],
        dest:'app/public/admin/js/app.min.js'
      },
      {
        src:[
          'app/public/admin/js/app.src.js'
        ],
        dest:'app/public/admin/js/app.min.js'
      }
    ]
  },
  html:{
    src:[
      'html/js/app.src.js'
    ],
    dest:'html/js/app.min.js'
  }
}
